=== lucasp149/MyDB/src/main/resources/Xml/client.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="zoneType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>
    <xs:complexType name="passportType">
        <xs:all>
            <xs:element name="number" type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>
    <xs:complexType name="cityType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="zone" type="zoneType"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>
    <xs:complexType name="addressType">
        <xs:all>
            <xs:element name="streetName" type="xs:string"/>
            <xs:element name="number" type="xs:int"/>
            <xs:element name="city" type="cityType"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>
    <xs:element name="client">
        <xs:complexType>
            <xs:all>
                <xs:element name="firstName" type="xs:string"/>
                <xs:element name="lastName" type="xs:string"/>
                <xs:element name="address" type="addressType"/>
                <xs:element name="passport" type="passportType"/>

            </xs:all>
        <xs:attribute name="id" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== lucasp149/MyDB/src/main/resources/Xml/client.xml
<?xml version="1.0" encoding="UTF-8"?>
<client id="20"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="client.xsd">

    <firstName>Secret Name</firstName>
    <lastName>Last Name</lastName>
    <address id="20">
        <streetName>Secret Address B1</streetName>
        <number>100</number>
        <city id="20">
            <name>Secret City B1</name>
            <zone id="20">
                <name>Secret Zone B1</name>
            </zone>
        </city>
    </address>
    <passport id="20">
        <number>LP149</number>
    </passport>

</client>
