=== lucasp149/MyDB/src/main/resources/Xml/product.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="zoneType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>
    <xs:complexType name="categoryType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>
    <xs:complexType name="cityType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="zone" type="zoneType"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>
    <xs:complexType name="addressType">
        <xs:all>
            <xs:element name="streetName" type="xs:string"/>
            <xs:element name="number" type="xs:int"/>
            <xs:element name="city" type="cityType"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>
    <xs:complexType name="depositType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="address" type="addressType"/>
        </xs:all>
        <xs:attribute name="id" use="required"/>
    </xs:complexType>
    <xs:element name="product">
        <xs:complexType>
            <xs:all>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="price" type="xs:decimal"/>
                <xs:element name="deposit" type="depositType"/>
                <xs:element name="category" type="categoryType"/>
            </xs:all>
            <xs:attribute name="id"/>
        </xs:complexType>

    </xs:element>
</xs:schema>

=== lucasp149/MyDB/src/main/resources/Xml/product.xml
<?xml version="1.0" encoding="UTF-8"?>
<product id="20"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="product.xsd">

    <name>Secret Product B1</name>
    <description>This is a secret product</description>
    <price>120</price>
    <deposit id="20">

        <name>Secret Deposit B1</name>
        <address id="20">
            <streetName>Secret Address B1</streetName>
            <number>110</number>
            <city id="20">
                <name>Secret City B1</name>
                <zone id="20">
                    <name>Secret Zone B1</name>
                </zone>
            </city>
        </address>

    </deposit>
    <category id="20">
        <name>Secret Category B1</name>
    </category>

</product>
